USE [master]
GO

/****** Object:  Database [H2tecBankingDB]    Script Date: 15-01-2018 16:21:11 ******/
CREATE DATABASE [H2tecBankingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'H2tecBankingDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\H2tecBankingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'H2tecBankingDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\H2tecBankingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [H2tecBankingDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [H2tecBankingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [H2tecBankingDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [H2tecBankingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [H2tecBankingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [H2tecBankingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [H2tecBankingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET RECOVERY FULL 
GO

ALTER DATABASE [H2tecBankingDB] SET  MULTI_USER 
GO

ALTER DATABASE [H2tecBankingDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [H2tecBankingDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [H2tecBankingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [H2tecBankingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [H2tecBankingDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [H2tecBankingDB] SET QUERY_STORE = OFF
GO

USE [H2tecBankingDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [H2tecBankingDB] SET  READ_WRITE 
GO


